from __future__ import annotations

import importlib.util
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = REPO_ROOT / "scripts" / "asana_api.py"
SPEC = importlib.util.spec_from_file_location("asana_api", MODULE_PATH)
ASANA_API = importlib.util.module_from_spec(SPEC)
assert SPEC and SPEC.loader
SPEC.loader.exec_module(ASANA_API)


class NormalizeAiAuthoredRichTextTests(unittest.TestCase):
    def test_rewrites_legacy_single_list_into_mixed_structure(self) -> None:
        raw = """
        <body>
          <strong>AI MESSAGE DISCLAIMER</strong>
          <ul>
            <li>This message was generated by AI to summarize implementation status and verification.</li>
            <li><strong>Status:</strong> Merged to <code>main</code>.</li>
            <li><strong>What changed:</strong></li>
            <li>First concrete change.</li>
            <li>Second concrete change.</li>
            <li><strong>Verification:</strong></li>
            <li><code>pnpm test</code></li>
          </ul>
        </body>
        """

        normalized = ASANA_API.normalize_ai_authored_rich_text(raw)

        self.assertEqual(
            normalized,
            (
                "<body><strong>AI MESSAGE DISCLAIMER</strong>"
                "<blockquote>This message was generated by AI to summarize implementation status and verification.</blockquote>"
                "<strong>Status:</strong><blockquote>Merged to <code>main</code>.</blockquote>"
                "<strong>What changed:</strong><ul><li>First concrete change.</li><li>Second concrete change.</li></ul>"
                "<strong>Verification:</strong><ul><li><code>pnpm test</code></li></ul>"
                "</body>"
            ),
        )

    def test_rewrites_inline_blob_without_forcing_bullets(self) -> None:
        raw = (
            "<body><strong>AI MESSAGE DISCLAIMER</strong> "
            "This message was generated by AI to summarize implementation status and verification. "
            "<strong>Status:</strong> Merged to <code>main</code>. "
            "<strong>Review:</strong> Please spot-check the screenshots."
            "</body>"
        )

        normalized = ASANA_API.normalize_ai_authored_rich_text(raw)

        self.assertEqual(
            normalized,
            (
                "<body><strong>AI MESSAGE DISCLAIMER</strong>"
                "<blockquote>This message was generated by AI to summarize implementation status and verification.</blockquote>"
                "<strong>Status:</strong><blockquote>Merged to <code>main</code>.</blockquote>"
                "<strong>Review:</strong><blockquote>Please spot-check the screenshots.</blockquote>"
                "</body>"
            ),
        )

    def test_preserves_existing_mixed_block_structure(self) -> None:
        raw = (
            "<body><strong>AI MESSAGE DISCLAIMER</strong>"
            "<blockquote>This message was generated by AI to summarize implementation status and verification.</blockquote>"
            "<strong>Status:</strong><blockquote>Merged to <code>main</code>.</blockquote>"
            "<strong>What changed:</strong><ul><li>First concrete change.</li></ul>"
            "</body>"
        )

        normalized = ASANA_API.normalize_ai_authored_rich_text(raw)

        self.assertEqual(normalized, raw)

    def test_compacts_pretty_printed_mixed_structure_to_avoid_empty_bullets(self) -> None:
        raw = """
        <body>
          <strong>AI MESSAGE DISCLAIMER</strong>
          <blockquote>This message was generated by AI to summarize implementation status and verification.</blockquote>
          <strong>What changed:</strong>
          <ul>
            <li>First concrete change.</li>
            <li>Second concrete change.</li>
          </ul>
          <strong>Verification:</strong>
          <ul>
            <li><code>pnpm test</code></li>
          </ul>
        </body>
        """

        normalized = ASANA_API.normalize_ai_authored_rich_text(raw)

        self.assertEqual(
            normalized,
            (
                "<body><strong>AI MESSAGE DISCLAIMER</strong>"
                "<blockquote>This message was generated by AI to summarize implementation status and verification.</blockquote>"
                "<strong>What changed:</strong><ul><li>First concrete change.</li><li>Second concrete change.</li></ul>"
                "<strong>Verification:</strong><ul><li><code>pnpm test</code></li></ul>"
                "</body>"
            ),
        )


if __name__ == "__main__":
    unittest.main()
